const exercises = [
  { "exercise": "Jogging on the spot", "duration": "00:00:30" },
  { "exercise": "Squat", "duration": "00:00:30" },
  { "exercise": "Jogging on the spot", "duration": "00:00:30" },
  { "exercise": "Squat", "duration": "00:00:30" },
  { "exercise": "Overhead side reaches", "duration": "00:00:30" },
  { "exercise": "Step back and arm high taps", "duration": "00:00:30" },
  { "exercise": "Overhead side reaches", "duration": "00:00:30" },
  { "exercise": "Step back and arm high taps", "duration": "00:00:30" },
  { "exercise": "Cross body arm lunges", "duration": "00:00:30" },
  { "exercise": "Reverse lunge and squats", "duration": "00:00:30" },
  { "exercise": "Cross body arm lunges", "duration": "00:00:30" },
  { "exercise": "Reverse lunge and squats", "duration": "00:00:30" },
  { "exercise": "Knee crosses", "duration": "00:00:30" },
  { "exercise": "Burpees", "duration": "00:00:30" },
  { "exercise": "Hamstring kicks", "duration": "00:00:30" },
  { "exercise": "Knee crosses", "duration": "00:00:30" },
  { "exercise": "Burpees", "duration": "00:00:30" },
  { "exercise": "Hamstring kicks", "duration": "00:00:30" },
  { "exercise": "Jumping jacks", "duration": "00:00:30" },
  { "exercise": "Step and squat", "duration": "00:00:30" },
  { "exercise": "Step reverse lunge", "duration": "00:00:30" },
  { "exercise": "Step across and squat", "duration": "00:00:30" },
  { "exercise": "Jumping jacks", "duration": "00:00:30" },
  { "exercise": "Rest. With weights", "duration": "00:01:00" },
  { "exercise": "Step and squat, weight arm curl", "duration": "00:00:45" },
  { "exercise": "Step off and croos sky press", "duration": "00:00:45" },
  { "exercise": "One leg step, arm cross and fly", "duration": "00:00:45" },
  { "exercise": "One leg step, dip and weight pull", "duration": "00:00:45" },
  { "exercise": "One leg step, arm cross and fly", "duration": "00:00:45" },
  { "exercise": "One leg step, dip and weight pull", "duration": "00:00:45" },
  { "exercise": "Reverse lunge, arm curl", "duration": "00:00:45" },
  { "exercise": "Hamstring kicks", "duration": "00:00:45" },
  { "exercise": "Rest. Lie down", "duration": "00:01:00" },
  { "exercise": "Step lie arm press, arc", "duration": "00:01:00" },
  { "exercise": "Step lie bench press", "duration": "00:01:00" },
  { "exercise": "Stomach 100 swim", "duration": "00:00:45" },
  { "exercise": "Sit ups", "duration": "00:00:30" },
  { "exercise": "Leg raises", "duration": "00:00:30" }
];
