// eslint-disable-next-line no-unused-vars
const exercises = [
  { exercise: 'Get ready', duration: 15 },
  { exercise: 'Jogging on the spot', duration: 30 },
  { exercise: 'Squat', duration: 30 },
  { exercise: 'Jogging on the spot', duration: 30 },
  { exercise: 'Squat', duration: 30 },
  { exercise: 'Overhead side reaches', duration: 30 },
  { exercise: 'Step back and arm high taps', duration: 30 },
  { exercise: 'Overhead side reaches', duration: 30 },
  { exercise: 'Step back and arm high taps', duration: 30 },
  { exercise: 'Cross body arm lunges', duration: 30 },
  { exercise: 'Reverse lunge and squats', duration: 30 },
  { exercise: 'Cross body arm lunges', duration: 30 },
  { exercise: 'Reverse lunge and squats', duration: 30 },
  { exercise: 'Knee crosses', duration: 30 },
  { exercise: 'Burpees', duration: 30 },
  { exercise: 'Hamstring kicks', duration: 30 },
  { exercise: 'Knee crosses', duration: 30 },
  { exercise: 'Burpees', duration: 30 },
  { exercise: 'Hamstring kicks', duration: 30 },
  { exercise: 'Jumping jacks', duration: 30 },
  { exercise: 'Step and squat', duration: 30 },
  { exercise: 'Step reverse lunge', duration: 30 },
  { exercise: 'Step across and squat', duration: 30 },
  { exercise: 'Jumping jacks', duration: 30 },
  { exercise: 'Rest. With weights', duration: 60 },
  { exercise: 'Step and squat, weight arm curl', duration: 45 },
  { exercise: 'Step off and croos sky press', duration: 45 },
  { exercise: 'One leg step, arm cross and fly', duration: 45 },
  { exercise: 'One leg step, dip and weight pull', duration: 45 },
  { exercise: 'One leg step, arm cross and fly', duration: 45 },
  { exercise: 'One leg step, dip and weight pull', duration: 45 },
  { exercise: 'Tricep overheads', duration: 45 },
  { exercise: 'Reverse lunge, arm curl', duration: 45 },
  { exercise: 'Hamstring kicks', duration: 45 },
  { exercise: 'Rest. Lie down', duration: 60 },
  { exercise: 'Arm press, arc', duration: 60 },
  { exercise: 'Bench press', duration: 60 },
  { exercise: 'Bench press, leg raise', duration: 60 },
  { exercise: 'Stomach 100 swim', duration: 45 },
  { exercise: 'Sit ups', duration: 45 },
  { exercise: 'Situp leg raises', duration: 45 },
  { exercise: 'Sitting twists', duration: 45 },
];
