const programs = [
  {
    id: 'program-30',
    title: '30 Minute Program',
    exercises: [
      { exercise: 'Get ready', duration: 15 },
      { exercise: 'Jogging on the spot', duration: 30 },
      { exercise: 'Squat', duration: 30 },
      { exercise: 'Jogging on the spot', duration: 30 },
      { exercise: 'Squat', duration: 30 },
      { exercise: 'Overhead side reaches', duration: 30 },
      { exercise: 'Step back and arm high taps', duration: 30 },
      { exercise: 'Overhead side reaches', duration: 30 },
      { exercise: 'Step back and arm high taps', duration: 30 },
      { exercise: 'Cross body arm lunges', duration: 30 },
      { exercise: 'Reverse lunge and squats', duration: 30 },
      { exercise: 'Cross body arm lunges', duration: 30 },
      { exercise: 'Reverse lunge and squats', duration: 30 },
      { exercise: 'Knee crosses', duration: 30 },
      { exercise: 'Burpees', duration: 30 },
      { exercise: 'Hamstring kicks', duration: 30 },
      { exercise: 'Knee crosses', duration: 30 },
      { exercise: 'Burpees', duration: 30 },
      { exercise: 'Hamstring kicks', duration: 30 },
      { exercise: 'Jumping jacks', duration: 30 },
      { exercise: 'Step and squat', duration: 30 },
      { exercise: 'Step reverse lunge', duration: 30 },
      { exercise: 'Step across and squat', duration: 30 },
      { exercise: 'Jumping jacks', duration: 30 },
      { exercise: 'Rest. With weights', duration: 60 },
      { exercise: 'Weighted cross press', duration: 60 },
      { exercise: 'Step and squat, weight arm curl', duration: 45 },
      { exercise: 'Step off and cross sky press', duration: 45 },
      { exercise: 'One leg step, arm cross and fly', duration: 45 },
      { exercise: 'One leg step, dip and weight pull', duration: 45 },
      { exercise: 'One leg step, arm cross and fly', duration: 45 },
      { exercise: 'One leg step, dip and weight pull', duration: 45 },
      { exercise: 'Tricep overheads', duration: 60 },
      { exercise: 'Weighted one-leg bend', duration: 60 },
      { exercise: 'Weighted one-leg bend', duration: 60 },
      { exercise: 'Hamstring kicks', duration: 30 },
      { exercise: 'Reverse lunge, arm curl', duration: 45 },
      { exercise: 'Hamstring kicks', duration: 30 },
      { exercise: 'Rest. Lie down', duration: 60 },
      { exercise: 'Arm press, arc', duration: 60 },
      { exercise: 'Bench press', duration: 60 },
      { exercise: 'Bench press, leg raise', duration: 60 },
      { exercise: 'Stomach 100 swim', duration: 45 },
      { exercise: 'Sit ups', duration: 45 },
      { exercise: 'Situp leg raises', duration: 45 },
      { exercise: 'Sitting twists', duration: 45 },
    ],
  },
  {
    id: 'program-55',
    title: '55 Minute Program',
    exercises: [
      // Warm-up & Mobility
      { exercise: 'Get ready', duration: 15 },
      { exercise: 'Brisk walk on the spot', duration: 60 },
      { exercise: 'Bodyweight step ups', duration: 60 },
      { exercise: 'Hip circles', duration: 45 },
      { exercise: 'Slow air squats', duration: 60 },
      { exercise: 'Bird dog', duration: 60 },
      { exercise: 'Cat cow stretch', duration: 60 },
      { exercise: 'Glute bridges', duration: 60 },
      { exercise: 'Rest and grab weights', duration: 30 },

      // Strength Circuit 1: Quads & Glutes
      { exercise: 'Step ups, left leg, five kilos', duration: 60 },
      { exercise: 'Step ups, right leg, five kilos', duration: 60 },
      { exercise: 'Short rest', duration: 30 },
      { exercise: 'Goblet squats, eight kilos', duration: 60 },
      { exercise: 'Forward lunges, three kilos', duration: 60 },
      { exercise: 'Short rest', duration: 30 },
      { exercise: 'Step ups, left leg, five kilos', duration: 60 },
      { exercise: 'Step ups, right leg, five kilos', duration: 60 },
      { exercise: 'Short rest', duration: 30 },
      { exercise: 'Goblet squats, eight kilos', duration: 60 },
      { exercise: 'Forward lunges, three kilos', duration: 60 },
      { exercise: 'Rest', duration: 30 },

      // Strength Circuit 2: Descending Control & Calves
      { exercise: 'Single leg deadlifts, left side, five kilos', duration: 60 },
      { exercise: 'Single leg deadlifts, right side, five kilos', duration: 60 },
      { exercise: 'Short rest', duration: 30 },
      { exercise: 'Slow step downs, left leg', duration: 60 },
      { exercise: 'Slow step downs, right leg', duration: 60 },
      { exercise: 'Calf raises, eight kilos', duration: 60 },
      { exercise: 'Short rest', duration: 30 },
      { exercise: 'Single leg deadlifts, left side, five kilos', duration: 60 },
      { exercise: 'Single leg deadlifts, right side, five kilos', duration: 60 },
      { exercise: 'Short rest', duration: 30 },
      { exercise: 'Slow step downs, left leg', duration: 60 },
      { exercise: 'Slow step downs, right leg', duration: 60 },
      { exercise: 'Calf raises, eight kilos', duration: 60 },
      { exercise: 'Rest and go to mat', duration: 30 },

      // Core & Stability
      { exercise: 'Plank', duration: 60 },
      { exercise: 'Side plank, left side', duration: 45 },
      { exercise: 'Side plank, right side', duration: 45 },
      { exercise: 'Russian twists, three kilos', duration: 60 },
      { exercise: 'Superman extensions', duration: 60 },
      { exercise: 'Rest and lie down', duration: 30 },

      // Deep Stretching & Flexibility
      { exercise: 'Left quad stretch', duration: 60 },
      { exercise: 'Right quad stretch', duration: 60 },
      { exercise: 'Left hamstring stretch', duration: 90 },
      { exercise: 'Right hamstring stretch', duration: 90 },
      { exercise: 'Pigeon pose, left side', duration: 90 },
      { exercise: 'Pigeon pose, right side', duration: 90 },
      { exercise: 'Left calf stretch', duration: 60 },
      { exercise: 'Right calf stretch', duration: 60 },
      { exercise: 'Left hip flexor stretch', duration: 60 },
      { exercise: 'Right hip flexor stretch', duration: 60 },
      { exercise: 'Butterfly stretch', duration: 60 },
      { exercise: 'Spinal twist, left', duration: 90 },
      { exercise: 'Spinal twist, right', duration: 90 },
      { exercise: 'Standing forward fold', duration: 120 },
      { exercise: 'Deep breathing and relaxation', duration: 180 },
    ],
  },
];
